version: '2'


services:
  auto:
    build: ./microservices/cliente-service
    depends_on:  
      - mongo
    environment:
      - PORT=4000
      - MONGODB_CNN=mongodb+srv://docker:Edward123456@cluster0.qvfuds8.mongodb.net/?retryWrites=true&w=majority
  concepto:
    build: ./microservices/concepto-service
    depends_on:  
      - mongo
    environment:
      - PORT=4000
      - MONGODB_CNN=mongodb:mongodb+srv://Edward:1234@cluster0.nlizucf.mongodb.net/?retryWrites=true&w=majority

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auto
      - concepto

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    