// Generated by https://quicktype.io

export interface IResGasto {
    total: number;
    gasto: Gasto[];
}

export interface Gasto {
    id: string,
    idcliente: string,
    idconcepto: string,
    caracteristica: string,
    valortotal: number,
}