version: '3'

services:
  api:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGODB_CNN=mongodb://mongo:28017/test
    ports:
      - "4000:4000"
  mongo:
    image: mongo
    ports:
      - "28017:28017"
      